{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-netpol
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: kgateway-system
        - podSelector: {}
        - ipBlock:
            cidr: {{ .Values.networkPolicy.vpcCidr }}
      ports:
        - port: {{ .Values.service.port }}
          protocol: TCP
  egress:
    - {}
{{- end }}
