namespace: monitoring
# ARN of the ALB target group for Grafana — set after terraform apply
# terraform output grafana_target_group_arn
grafanaTGBArn: "arn:aws:elasticloadbalancing:us-east-1:242969680553:targetgroup/shopmesh-grafana-tg/98fbc1e2bf85c809"
