apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-for-fluent-bit
    targetRevision: 0.1.34
    helm:
      releaseName: fluent-bit
      values: |
        cloudWatch:
          enabled: true
          region: us-east-1
          logGroupName: /shopmesh/eks
          logStreamPrefix: eks/
          autoCreateGroup: true
        firehose:
          enabled: false
        kinesis:
          enabled: false
        elasticsearch:
          enabled: false
        tolerations:
          - operator: Exists
        serviceAccount:
          name: fluent-bit
          annotations:
            eks.amazonaws.com/role-arn: "arn:aws:iam::686591366739:role/shopmesh-irsa-fluent-bit"
  destination:
    server: https://kubernetes.default.svc
    namespace: amazon-cloudwatch
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
