apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd
  namespace: {{ .Values.namespace }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/part-of: argocd
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
